function ddt = myFunction(in1,g,m,k)
%MYFUNCTION
%    DDT = MYFUNCTION(IN1,G,M,K)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Mar-2017 13:44:57

x = in1(:,1);
xdot = in1(:,4);
y = in1(:,2);
ydot = in1(:,5);
z = in1(:,3);
zdot = in1(:,6);
t2 = sin(z);
ddt = ydot.*(g.*y.*2.0+k.*t2.*x)+xdot.*(m.*x.*2.0+k.*t2.*y)+zdot.*(z.*2.0+k.*x.*y.*cos(z));
